### ISSUE TITLE
Does not support GTK2 apps

### ISSUE THREAD

**Issue by nsrosenqvist** [p-e-w/plotinus#14]
I don't know if GTK2 apps support is on the roadmap but it would be great if it were. Many menu heavy apps are still built with GTK2, eg. stable GIMP and Inkscape, and I'd love to be able to use Plotinus for those apps.

**Comment by p-e-w** [comment]
I've thought long and hard about this, and decided that I'm not going to add GTK2 support.

The only major apps that still use GTK2 by default are Inkscape, GIMP and Chrome, and all three have had GTK3 branches for years. The solution here is that these projects get their act together and update their toolkit, rather than a newly written program like Plotinus supporting a library that has been obsolete since 2011.

I know this sucks, but riddling Plotinus' source code with `#ifdef`s would do more harm than good. Besides, not being able to use Plotinus is just one of the many issues GTK2 apps have on a modern desktop. Moving them to GTK3 is the only way forward.
