### ISSUE TITLE
Application Conflict

### ISSUE THREAD

**Issue by ElectricPrism** [p-e-w/plotinus#37]
This is such a helpful and amazing tool I want to see it interface out of box with as many applications as possible.

I noticed it doesn't work on Firefox-Nightly,
Thunderbird-Nightly,
it works with GIMP-GTK3 branch however a keybinding for GIMP needs to be unset (Is it possible to supersede application keybindings?)
I guess it doesn't work in LibreOffice (Which is a shame because the menu must have at least 150+ entries that are hard to navigate)

I am wondering what would need to be done to break down these barriers for wider usage.

**Comment by p-e-w** [comment]
> I noticed it doesn't work on Firefox-Nightly, Thunderbird-Nightly,

Those applications don't use GTK+ widgets, so there's nothing I can do about that.

> it works with GIMP-GTK3 branch however a keybinding for GIMP needs to be unset (Is it possible to supersede application keybindings?)

Overriding application keybindings sounds like a bad idea. Plotinus is an optional enhancement, over which application logic should always take precedence, otherwise some applications might not work correctly anymore. 

> I guess it doesn't work in LibreOffice

Yes, it does! (Assuming you are running a GTK+ 3.0 build.)

**Comment by magnetophon** [comment]
For me, LibreOffice also doesn't work.
It's built with gtk3 and running  on NixOS.
